### ISSUE TITLE
Overclocking not working

### ISSUE THREAD

**Issue by Youngv** [n4ru/MiNOVA#4]
I use the MiNOVA on a 1070 card with config  
```
{
    "threshold": 90,
    "kill": "tskill ethdcrminer64",
    "path": "\\bin\\ethdcrminer64.exe xxxxxxxxxxxxxxxxxxxxxxx",
    "reboot": "shutdown -r -t 00",
    "restartApp": 60,
    "rebootRig": 360,
    "core": 1900,
    "mem": 9000,
    "power": 150,
    "p0": false
}
```
but the clock not changed, I have to change the clock by myself.

**Comment by n4ru** [comment]
Are you using the release or the latest commit? There's a lot of new changes I've made and there's going to be a fully overhauled version in the next 2-3 weeks.

**Comment by n4ru** [comment]
Also, the core/mem config is supposed to be additional MHz, not total. So if you were going from 1400 to 1900 you'd set 500 instead of 1900 - that's probably why it's failing.

**Comment by Youngv** [comment]
I use the release, I don't know how to use the  latest commit without the Eth-NOVA.exe file. I just tried the release with additional MHz config, still not working.

**Comment by Youngv** [comment]
Any updates?
